import { NATIVE_SOL, TOKENS } from './tokens';

export const FARMS = [
  {
    symbol: 'RAYDIUM-RAY-whETH',
    name: 'RAY-whETH',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.whETH },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: 'DWk7Xg8q3jotVGuVBteJ31PjdmEn2iyjQTectbrkjBaq',
    decimals: TOKENS.RAY.decimals,
    logos: [rayLogo, whETHLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.RAY, TOKENS.whETH],
    platform: FARM_PLATFORMS.RAYDIUM,
    marginIndex: 75,
    maxPositionLimitInUsd: 9000000,
    isNew: isFarmNew('30/05/2022'),
    tags: [],
    link: 'https://raydium.io/liquidity/add/?coin0=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&coin1=7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs&fixed=coin0&ammId=E9Bg7Fg5TVSXge9ADN7fDjsR7MXRKsgq3STJ9aCdZoTZ'
  },
  {
    symbol: 'RAYDIUM-wALEPH-USDC',
    name: 'wALEPH-USDC',
    coin: { ...TOKENS.wALEPH },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.wALEPH },

    mintAddress: '3qn11mgGLAqZHucw8vwL2hsxRSHpnw2Jjo2HxicFN7hi',
    decimals: TOKENS.wALEPH.decimals,
    logos: [wAlephLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.wALEPH, TOKENS.USDC],
    platform: FARM_PLATFORMS.RAYDIUM,
    marginIndex: 66,
    maxPositionLimitInUsd: 500000,
    isNew: isFarmNew('03/05/2022'),
    tags: [],
    link: 'https://raydium.io/liquidity/add/?coin0=3UCMiSnkcnkPE1pgQ5ggPCBv6dXgVUy16TmMUe1WpG9x&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=2Cat6zKJm5HRsqKs7W14cuzdrDQXByu8c9bAFcM9uHvY'
  },

  {
    symbol: 'RAYDIUM-SLCL-USDC',
    name: 'SLCL-USDC',
    coin: { ...TOKENS.SLCL },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SLCL },

    mintAddress: '5jQ9jc92SUmYsQ1JVHDuyUqctdtfwNWjvdGLHKPnzFT',
    decimals: TOKENS.SLCL.decimals,
    logos: [slclLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SLCL, TOKENS.USDC],
    platform: FARM_PLATFORMS.RAYDIUM,
    marginIndex: 67,
    maxPositionLimitInUsd: 500000,
    isNew: isFarmNew('29/04/2022'),
    tags: []
  },
  {
    symbol: 'RAYDIUM-stSOL-USDC',
    name: 'stSOL-USDC',
    coin: { ...TOKENS.stSOL },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.wLDO },

    mintAddress: 'HDUJMwYZkjUZre63xUeDhdCi8c6LgUDiBqxmP3QC3VPX',
    decimals: TOKENS.stSOL.decimals,
    logos: [stSolLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.stSOL, TOKENS.USDC],
    platform: FARM_PLATFORMS.RAYDIUM,
    marginIndex: 59,
    maxPositionLimitInUsd: 9000000,
    isNew: isFarmNew('04/04/2022'),
    tags: []
  },
  {
    symbol: 'RAYDIUM-stSOL-USDT',
    name: 'stSOL-USDT',
    coin: { ...TOKENS.stSOL },
    pc: { ...TOKENS.USDT },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.wLDO },

    mintAddress: '2pdg9vAH8GsTTWSSP3Za6j5ts4Nzs6tEbNterVe9H62H',
    decimals: TOKENS.stSOL.decimals,
    logos: [stSolLogo, usdtLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.stSOL, TOKENS.USDT],
    platform: FARM_PLATFORMS.RAYDIUM,
    marginIndex: 60,
    maxPositionLimitInUsd: 9000000,
    isNew: isFarmNew('04/04/2022'),
    tags: []
  },

  {
    symbol: 'RAYDIUM-BTC-stSOL',
    name: 'BTC-stSOL',
    coin: { ...TOKENS.BTC },
    pc: { ...TOKENS.stSOL },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.wLDO },

    mintAddress: '94Y3jaf96ysGqebzRP71isD7RKxmuhkyXK88b16ToJhE',
    decimals: TOKENS.BTC.decimals,
    logos: [btcLogo, stSolLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.BTC, TOKENS.stSOL],
    platform: FARM_PLATFORMS.RAYDIUM,
    marginIndex: 61,
    maxPositionLimitInUsd: 9000000,
    isNew: isFarmNew('04/04/2022'),
    tags: []
  },

  {
    symbol: 'RAYDIUM-ETH-stSOL',
    name: 'ETH-stSOL',
    coin: { ...TOKENS.whETH },
    pc: { ...TOKENS.stSOL },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.wLDO },

    mintAddress: 'D7F986x22g9uckCbQabpcw8HuJk8zRcAteDLbcCUVjm1',
    decimals: TOKENS.whETH.decimals,
    logos: [whETHLogo, stSolLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.whETH, TOKENS.stSOL],
    platform: FARM_PLATFORMS.RAYDIUM,
    marginIndex: 62,
    maxPositionLimitInUsd: 9000000,
    isNew: isFarmNew('04/04/2022'),
    tags: []
  },
  {
    symbol: 'SVT-USDC',
    name: 'SVT-USDC',
    coin: { ...TOKENS.SVT },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SVT },

    mintAddress: 'HXLkojxGWSUwjagzRXMFRgmnNxkcKrFHvq4ZCZeNvBJL',
    decimals: TOKENS.SVT.decimals,
    logos: [SVTLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SVT, TOKENS.USDC],
    marginIndex: 999999,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=svtMpL5eQzdmB3uqK9NXaQkq8prGZoKQFNVJghdWCkV&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=3rY1TU9NEkExmkVt9ouNL4FSoLdcCxmNp8rbQFaY8MQa',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('17/01/2022'),
    tags: []
  },
  {
    symbol: 'SLC-USDC',
    name: 'SLC-USDC',
    coin: { ...TOKENS.SLC },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SLC },

    mintAddress: '4A3kqZBJu581eFePXL1dTLfxEkjZPWJFgj4tJmP6mQQp',
    decimals: TOKENS.SLC.decimals,
    logos: [SLCLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SLC, TOKENS.USDC],
    marginIndex: 99999,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=METAmTMXwdb8gYzyCPfXXFmZZw4rUsXX58PNsDg7zjL&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=84Sk8vke7cSvKeLuEv6Y59GUJi9dKZUQTc3nxnNqKaNS',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('25/04/2022'),
    tags: []
  },
  {
    symbol: 'MBS-USDC',
    name: 'MBS-USDC',
    coin: { ...TOKENS.MBS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MBS },

    mintAddress: 'BAgSWaPZpsQKyZJdvB5KyvmCNj6hzczzentt5FhDCVHb',
    decimals: TOKENS.MBS.decimals,
    logos: [MBSLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.MBS, TOKENS.USDC],
    marginIndex: 54,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=Fm9rHUTF5v3hwMLbStjZXqNBBoZyGriQaFM6sTFz3K8A&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=6eRECBcCVP82AvAd6Di4rZApa2btLf8RDUqrTigt4hS4',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('30/12/2021'),
    tags: []
  },
  {
    symbol: 'PRISM-USDC',
    name: 'PRISM-USDC',
    coin: { ...TOKENS.PRISM },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.PRISM },

    mintAddress: '3baYkTcudvSFMe25UpZcBfdp4FA5kL2E4pfaeJ8AiYJB',
    decimals: TOKENS.PRISM.decimals,
    logos: [PRISMLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.PRISM, TOKENS.USDC],
    marginIndex: 53,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=PRSMNsEPqhGVCH1TtWiJqPjJyh2cKrLostPZTNy1o5x&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=4ZYiiVakejxGyJ3tuBzYWoHyEV1rk7Hm7viydG6DNaUN',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('25/04/2022'),
    tags: []
  },
  {
    symbol: 'CHICKS-USDC',
    name: 'CHICKS-USDC',
    coin: { ...TOKENS.CHICKS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.CHICKS },

    mintAddress: 'CPzmcw81a6PDasSXhVLfDRKuTJXZPUqocS9VFf5zCFhs',
    decimals: TOKENS.CHICKS.decimals,
    logos: [CHICKSLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.CHICKS, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=cxxShYRVcepDudXhe7U62QHvw8uBJoKFifmzggGKVC2&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=ELN2aYLwG92CRCC6XGcWMMb1qtfnQX5deJ8d1cH6V1Zu',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('02/01/2022'),
    tags: []
  },
  {
    symbol: 'MEAN-RAY',
    name: 'MEAN-RAY',
    coin: { ...TOKENS.MEAN },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MEAN },

    mintAddress: 'H9wUyrxpAErmdNVPitpHSXgwoomoh91ggJKPWtQQoCn1',
    decimals: TOKENS.MEAN.decimals,
    logos: [MEANLogo, rayLogo],
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.MEAN, TOKENS.RAY],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=MEANeD3XDdUmNMsRGjASkSWdC8prLYsoRJ61pPeHctD&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=HJNaZ5dDrKWKqo6JiBqjNvqfDFUtPVxS2fotbCdTw7pm',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('02/01/2022'),
    tags: []
  },
  {
    symbol: 'REAL-USDC',
    name: 'REAL-USDC',
    coin: { ...TOKENS.REAL },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.REAL },

    mintAddress: 'EN43tp8xdkcM8RYSJ4msFHMPTJRXKhUteVYBDJLwTvr3',
    decimals: TOKENS.REAL.decimals,
    logos: [REALLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.REAL, TOKENS.USDC],
    marginIndex: 52,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=AD27ov5fVU2XzwsbvnFvb1JpCBaCB5dRXrczV9CqSVGb&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=A7ZxDrK9LSkVXhfRTu2pRCinwYfdxW2kK6DaJk12jRWw',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('25/12/2021'),
    tags: []
  },
  {
    symbol: 'CRWNY-USDC',
    name: 'CRWNY-USDC',
    coin: { ...TOKENS.CRWNY },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.CRWNY },

    mintAddress: 'H3D9Gyi4frRLW6bS9vBthDVDJyzyRJ6XhhpP6PJGWaDC',
    decimals: TOKENS.CRWNY.decimals,
    logos: [CRWNYLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.CRWNY, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=CRWNYkqdgvhGGae9CKfNka58j6QQkaD5bLhKXvUYqnc1&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=4ELBQuq3ivhLamfCT36As5sXLkQDWRJw1pJ9JVFLp6gK',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/12/2021'),
    tags: []
  },
  {
    symbol: 'CRWNY-RAY',
    name: 'CRWNY-RAY',
    coin: { ...TOKENS.CRWNY },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.CRWNY },

    mintAddress: '5Cz9wGStNjiUg81q8t6sJJeckuT2C14CYSfyQbtYirSX',
    decimals: TOKENS.CRWNY.decimals,
    logos: [CRWNYLogo, rayLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.CRWNY, TOKENS.RAY],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.CRWNY.mintAddress}&coin1=${TOKENS.RAY.mintAddress}&fixed=coin0&ammId=HARRXESCwid3xMi2qThag1PXzmp6rDhAzMR9THhFRQGf`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/12/2021'),
    tags: []
  },
  {
    symbol: 'RUN-USDC',
    name: 'RUN-USDC',
    coin: { ...TOKENS.RUN },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RUN },

    mintAddress: 'CjTLvvKSQdEujcSzeZRYgk4w1DpuXBbMppLHaxZyz11Y',
    decimals: TOKENS.RUN.decimals,
    logos: [RUNLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.RUN, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=6F9XriABHfWhit6zmMUYAQBSy6XK5VF1cHXuW5LDpRtC&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=zuivKkgkNFFkV9jfNpsU1p5tWNbDWUEx5XX16m4k2Ej',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/12/2021'),
    tags: []
  },
  {
    symbol: 'TTT-USDC',
    name: 'TTT-USDC',
    coin: { ...TOKENS.TTT },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.TTT },

    mintAddress: '84fmrerHGohoRf4iLPDQ1KG4CjSjCRksYWGzjWfCRM8a',
    decimals: TOKENS.TTT.decimals,
    logos: [TTTLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.TTT, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.TTT.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=HcqHvH27wk42L1ND5YPhLDJu7oGsU7HGSreMiXdq5LNK`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/12/2021'),
    tags: []
  },
  {
    symbol: 'BOKU-USDC',
    name: 'BOKU-USDC',
    coin: { ...TOKENS.BOKU },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.BOKU },

    mintAddress: '8jjQn5Yagb6Nm2WGAxPW1bcGqrTWpg5adf6QukXEarcP',
    decimals: TOKENS.BOKU.decimals,
    logos: [BOKULogo, usdcLogo],
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.BOKU, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.BOKU.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=FsERtRjCEQNyND3ccnMGrd61ntPmJ3tbZs4vvcCzMr1L`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/12/2021'),
    tags: []
  },
  {
    symbol: 'XTAG-USDC',
    name: 'XTAG-USDC',
    coin: { ...TOKENS.XTAG },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.XTAG },

    mintAddress: 'GCEQbLg4ik5YJ4CMcbtuVqEc4sjLdSGy34rFk1CtGjdg',
    decimals: TOKENS.XTAG.decimals,
    logos: [XTAGLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.XTAG, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.XTAG.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=Hv1BFhyADPjYXTqEeMgwzoybnNwYrHXNv7U2VjcAuEDr`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/12/2021'),
    disabled: true,
    tags: []
  },
  {
    symbol: 'RAYDIUM-SOL-USDT',
    name: 'SOL-USDT',
    coin: { ...NATIVE_SOL },
    pc: { ...TOKENS.USDT },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: 'Epm4KfTj4DMrvqn6Bwg2Tr2N8vhQuNbuK8bESFp4k33K',
    decimals: NATIVE_SOL.decimals,
    logos: [solLogo, usdtLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [NATIVE_SOL, TOKENS.USDT],
    marginIndex: 51,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=sol&coin1=Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB&fixed=coin0&ammId=7XawhbbxtsRcQA8KTkHT9f9nc6d69UwqCDh6U5EEbEmX',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('10/12/2021'),
    tags: []
  },
  {
    symbol: 'RAYDIUM-SOL-USDC',
    name: 'SOL-USDC',
    coin: { ...NATIVE_SOL },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: '8HoQnePLqPj4M7PUDzfw8e3Ymdwgc7NLGnaTUapubyvu',
    decimals: NATIVE_SOL.decimals,
    logos: [solLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [NATIVE_SOL, TOKENS.USDC],
    marginIndex: 50,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=sol&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('10/12/2021'),
    tags: []
  },
  {
    symbol: 'SRM-USDC',
    name: 'SRM-USDC',
    coin: { ...TOKENS.SRM },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },

    mintAddress: '9XnZd82j34KxNLgQfz29jGbYdxsYznTWRpvZE3SRE7JG',
    decimals: TOKENS.SRM.decimals,
    logos: [srmLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SRM, TOKENS.USDC],
    marginIndex: 38,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=8tzS7SkUZyHPQY7gLqsMCXZ5EDCgjESUHcB17tiR1h3Z',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/11/2021'),
    disabled: true,
    tags: []
  },
  {
    symbol: 'wbWBNB-USDC',
    name: 'wbWBNB-USDC',
    coin: { ...TOKENS.wbWBNB },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },
    mintAddress: 'FEsEfEJJSfiMQcshUgZ5UigfytfGRQ3z5puyF6DXDp9C',
    decimals: TOKENS.wbWBNB.decimals,
    logos: [wbWBNBLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.wbWBNB, TOKENS.USDC],
    marginIndex: 49,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.wbWBNB.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=Fb1WR1kYvG1tHu4pwAxXQpdKT8Grh9i7ES9rZusLg7D6`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('04/12/2021'),
    tags: [],
    highLiquidity: true,
    disabled: true
  },
  {
    symbol: 'MIMO-SOL',
    name: 'MIMO-SOL',
    coin: { ...TOKENS.MIMO },
    pc: { ...NATIVE_SOL },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MIMO },

    mintAddress: 'HUJ1opSk8AiPfDT47r7n4hTiK2EXgrR3Msy7T8q1BywS',
    decimals: TOKENS.MIMO.decimals,
    logos: [MIMOLogo, solLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.MIMO, NATIVE_SOL],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=9TE7ebz1dsFo1uQ2T4oYAKSm39Y6fWuHrd6Uk6XaiD16&coin1=sol&fixed=coin0&ammId=DqYSvijBXydSx9GfvVDjEzUg5StLLrkqZVPzsU2FeVZ2',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('04/12/2021'),
    disabled: true,
    tags: []
  },

  // {
  //   symbol: 'wePEOPLE-USDC',
  //   name: 'wePEOPLE-USDC',
  //   coin: { ...TOKENS.wePEOPLE },
  //   pc: { ...TOKENS.USDC },
  //   reward: { ...TOKENS.RAY },
  //   rewardB: { ...TOKENS.SRM },
  //
  //   mintAddress: '3e5ZCKi4etorpV4pv1fSckP5iJD67xcUkx3RtFCZhbzD',
  //   decimals: TOKENS.wePEOPLE.decimals,
  //   logos: [wePEOPLELogo, usdcLogo],
  //   dualYield: false,
  //   liquidityMining: false,
  //   totalTulipEmission: 0,
  //   saber: false,
  //   coins: [TOKENS.wePEOPLE, TOKENS.USDC],
  //   marginIndex: 11111,
  //   slippageWarning: false,
  //   maxPositionLimitInUsd: 90000000,
  //   link: 'https://raydium.io/liquidity/?ammId=GfvqUB36CPfqZDz5ntQ2YsoKRwg1MCewmurhc7jw3P5s',
  //   rewardEndSlot: 93847628,
  //   platform: FARM_PLATFORMS.RAYDIUM,
  //   isNew: isFarmNew('04/12/2021'),
  //   tags: [],
  // },
  {
    symbol: 'DFL-USDC',
    name: 'DFL-USDC',
    coin: { ...TOKENS.DFL },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.DFL },

    mintAddress: 'Fffijd6UVJdQeLVXhenS8YcsnMUdWJqpbBeH42LFkXgS',
    decimals: TOKENS.DFL.decimals,
    logos: [DFLLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.DFL, TOKENS.USDC],
    marginIndex: 47,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=DFL1zNkaGPWm1BqAVqRjCZvHmwTFrEaJtbzJWgseoNJh&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=8GJdzPuEBPP3BHJpcspBcfpRZV4moZMFwhTAuXebaPL8',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('28/11/2021'),
    tags: []
  },
  {
    symbol: 'APT-USDC',
    name: 'APT-USDC',
    coin: { ...TOKENS.APT },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.APT },

    mintAddress: 'Hk8mDAJFq4E9kF3DtNgPFwzbo5kbeiusNFJgWmo3LoQ5',
    decimals: TOKENS.APT.decimals,
    logos: [APTLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.APT, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: 'https://raydium.io/liquidity/add/?coin0=APTtJyaRX5yGTsJU522N4VYWg3vCvSb65eam5GrPT5Rt&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=4crhN3D8R5rnZd66q9b32P7K649e5XdzCfPMPiTzBceH',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('26/11/2021'),
    disabled: true,
    tags: []
  },
  {
    symbol: 'SHILL-USDC',
    name: 'SHILL-USDC',
    coin: { ...TOKENS.SHILL },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SHILL },

    mintAddress: 'CnUhYBtQEbSBZ76bgxAouVCTCb8rofZzwerVF5z5LREJ',
    decimals: TOKENS.SHILL.decimals,
    logos: [SHILLLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SHILL, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: 'https://raydium.io/liquidity/add/?coin0=6cVgJUqo4nmvQpbgrDZwyfd6RwWw5bfnCamS3M9N1fd&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=FTyJCLwQ3YvVfanJp8mtC2eqmvZPpzSpmNLqWpaPaXbC',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('26/11/2021'),
    tags: []
  },
  {
    symbol: 'SONAR-USDC',
    name: 'SONAR-USDC',
    coin: { ...TOKENS.SONAR },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SONAR },

    mintAddress: '2tAcfqJ1YYjpGLqwh76kyNt9VaNFDd4fJySfH6SmWfKt',
    decimals: TOKENS.SONAR.decimals,
    logos: [SonarLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SONAR, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: 'https://raydium.io/liquidity/add/?coin0=sonarX4VtVkQemriJeLm6CKeW3GDMyiBnnAEMw1MRAE&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=CrWbfKwyAaUfYctXWF9iaDUP4AH5t6k6bbaWnXBL8nHm',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('26/11/2021'),
    tags: []
  },
  {
    symbol: 'CWAR-USDC',
    name: 'CWAR-USDC',
    coin: { ...TOKENS.CWAR },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.CWAR },

    mintAddress: 'HjR23bxn2gtRDB2P1Tm3DLepAPPZgazsWJpLG9wqjnYR',
    decimals: TOKENS.CWAR.decimals,
    logos: [CWARLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.CWAR, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: 'https://raydium.io/liquidity/add/?coin0=HfYFjMKNZygfMC8LsQ8LtpPsPxEJoXJx4M6tqi75Hajo&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=13uCPybNakXHGVd2DDVB7o2uwXuf9GqPFkvJMVgKy6UJ',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('26/11/2021'),
    tags: []
  },
  {
    symbol: 'GENE-USDC',
    name: 'GENE-USDC',
    coin: { ...TOKENS.GENE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.GENE },

    mintAddress: '7GKvfHEXenNiWYbJBKae89mdaMPr5gGMYwZmyC8gBNVG',
    decimals: TOKENS.GENE.decimals,
    logos: [GENELogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.GENE, TOKENS.USDC],
    marginIndex: 45,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: 'https://raydium.io/liquidity/add/?coin0=GENEtH5amGSi8kHAtQoezp1XEXwZJ8vcuePYnXdKrMYz&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=Enq8vJucRbkzKA1i1PahJNhMyUTzoVL5Cs8n5rC3NLGn',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('22/11/2021'),
    tags: []
  },
  {
    symbol: 'GENE-RAY',
    name: 'GENE-RAY',
    coin: { ...TOKENS.GENE },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.GENE },

    mintAddress: '3HzXnc1qZ8mGqun18Ck3KA616XnZNqF1RWbgYE2nGRMA',
    decimals: TOKENS.GENE.decimals,
    logos: [GENELogo, rayLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.GENE, TOKENS.RAY],
    marginIndex: 46,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: 'https://raydium.io/liquidity/add/?coin0=GENEtH5amGSi8kHAtQoezp1XEXwZJ8vcuePYnXdKrMYz&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=8FrCybrh7UFznP1hVHg8kXZ8bhii37c7BGzmjkdcsGJp',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('22/11/2021'),
    tags: []
  },
  {
    symbol: 'weMANA-USDC',
    name: 'weMANA-USDC',
    coin: { ...TOKENS.weMANA },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },

    mintAddress: 'HpUkVAPRJ5zNRuJ1ZwMXEhbMHL3gSuPb2QuSER9YUd3a',
    decimals: TOKENS.weMANA.decimals,
    logos: [weMANALogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.weMANA, TOKENS.USDC],
    marginIndex: 11111,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.weMANA.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=7Z1c6GHutf3q2MNheyFE8KMNVEALuiPaqoEMyjbCbuku`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('21/11/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'weSAND-USDC',
    name: 'weSAND-USDC',
    coin: { ...TOKENS.weSAND },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },

    mintAddress: '3dADrQa7utyiCsaFeVk9r7oebW1WheowhKo5soBYKBVT',
    decimals: TOKENS.weSAND.decimals,
    logos: [weSANDLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.weSAND, TOKENS.USDC],
    marginIndex: 11111,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.weSAND.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=3cmPpX8kKzEra2umtLCDxMfjma82ELtAMaSYVmdaNLxi`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('21/11/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'CAVE-USDC',
    name: 'CAVE-USDC',
    coin: { ...TOKENS.CAVE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.CAVE },

    mintAddress: '5Gba1k3fU7Vh7UtAiBmie9vhQNNq1JfEwgn1DPGZ7NKQ',
    decimals: TOKENS.CAVE.decimals,
    logos: [CaveLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.CAVE, TOKENS.USDC],
    marginIndex: 48,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: 'https://raydium.io/liquidity/add/?coin0=4SZjjNABoqhbd4hnapbvoEPEqT8mnNkfbEoAwALf1V8t&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('04/12/2021'),
    tags: [],

    // highLiquidity: true,
    disabled: true
  },
  {
    symbol: 'weAXS-USDC',
    name: 'weAXS-USDC',
    coin: { ...TOKENS.weAXS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },

    mintAddress: '6PSoJQ7myQ1BJtbQC6oiWR8HSecQGyoWsPYTZRJo2ci3',
    decimals: TOKENS.weAXS.decimals,
    logos: [weAXSLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.weAXS, TOKENS.USDC],
    marginIndex: 11111,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.weAXS.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=HopVRTvFvRe1ED3dRCQrt1h5onkMvY3tKUHRVQMc7MMH`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('21/11/2021'),
    tags: []
  },
  {
    symbol: 'weDYDX-USDC',
    name: 'weDYDX-USDC',
    coin: { ...TOKENS.weDYDX },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },
    mintAddress: 'BjkkMZnnzmgLqzGErzDbkk15ozv48iVKQuunpeM2Hqnk',
    decimals: TOKENS.weDYDX.decimals,
    logos: [weDYDXLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.weDYDX, TOKENS.USDC],
    marginIndex: 44,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.weDYDX.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=CbGQojcizFEHn3woL7NPu3P9BLL1SWz5a8zkL9gks24q`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('21/11/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'weSHIB-USDC',
    name: 'weSHIB-USDC',
    coin: { ...TOKENS.weSHIB },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },

    mintAddress: 'AcjX5pmTMGSgxkdxc3r82r6WMKBvS6eQXXFz5ck5KKUa',
    decimals: TOKENS.weSHIB.decimals,
    logos: [weSHIBLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.weSHIB, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 4000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.weSHIB.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=SU7vPveBjEuR5tgQwidRqqTxn1WwraHpydHHBpM2W96`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('21/11/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'STARS-USDC',
    name: 'STARS-USDC',
    coin: { ...TOKENS.STARS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.STARS },

    mintAddress: 'FJ68q7NChhETcGVdinMbM2FF1Cy79dpmUi6HC83K55Hv',
    decimals: TOKENS.STARS.decimals,
    logos: [starsLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.STARS, TOKENS.USDC],
    marginIndex: 43,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: 'https://raydium.io/liquidity/add/?coin0=HCgybxq5Upy8Mccihrp7EsmwwFqYZtrHrsmsKwtGXLgW&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/11/2021'),
    tags: []
  },
  {
    symbol: 'weSUSHI-USDC',
    name: 'weSUSHI-USDC',
    coin: { ...TOKENS.weSUSHI },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },
    mintAddress: '3wVrtQZsiDNp5yTPyfEzQHPU6iuJoMmpnWg6CTt4V8sR',
    decimals: TOKENS.weSUSHI.decimals,
    logos: [weSushiLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.weSUSHI, TOKENS.USDC],
    marginIndex: 41,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.weSUSHI.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=9SWy6nbSVZ44XuixEvHpona663pZPpVgzXQ3N7muG4ou`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/11/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'weUNI-USDC',
    name: 'weUNI-USDC',
    coin: { ...TOKENS.weUNI },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },
    mintAddress: 'EEC4QnT41py39QaYnzQnoYQEtDUDNa6Se8SBDgfPSN2a',
    decimals: TOKENS.weSUSHI.decimals,
    logos: [weUNILogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.weUNI, TOKENS.USDC],
    marginIndex: 42,
    slippageWarning: false,
    maxPositionLimitInUsd: 90000000,
    link: `https://raydium.io/liquidity/add/?coin0=${TOKENS.weUNI.mintAddress}&coin1=${TOKENS.USDC.mintAddress}&fixed=coin0&ammId=8J5fa8WBGaDSv8AUpgtqdh9HM5AZuSf2ijvSkKoaCXCi`,
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/11/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'whETH-USDC',
    name: 'whETH-USDC',
    coin: { ...TOKENS.whETH },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },
    mintAddress: '3529SBnMCDW3S3xQ52aABbRHo7PcHvpQA4no8J12L5eK',
    decimals: TOKENS.whETH.decimals,
    logos: [whETHLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.whETH, TOKENS.USDC],
    marginIndex: 39,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=EoNrn8iUhwgJySD1pHu8Qxm5gSQqLK3za4m8xzD2RuEb',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/11/2021'),
    tags: []
  },
  {
    symbol: 'whETH-SOL',
    name: 'whETH-SOL',
    coin: { ...TOKENS.whETH },
    pc: { ...NATIVE_SOL },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },
    mintAddress: '3hbozt2Por7bcrGod8N7kEeJNMocFFjCJrQR16TQGBrE',
    decimals: TOKENS.whETH.decimals,
    logos: [whETHLogo, solLogo],
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.whETH, NATIVE_SOL],
    marginIndex: 40,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs&coin1=sol&fixed=coin0&ammId=4yrHms7ekgTBgJg77zJ33TsWrraqHsCXDtuSZqUsuGHb',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/11/2021'),
    tags: []
  },
  {
    symbol: 'FRKT-SOL',
    name: 'FRKT-SOL',
    coin: { ...TOKENS.FRKT },
    pc: { ...NATIVE_SOL },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.FRKT },

    mintAddress: 'HYUKXgpjaxMXHttyrFYtv3z2rdhZ1U9QDH8zEc8BooQC',
    decimals: TOKENS.FRKT.decimals,
    logos: [frktLogo, solLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.FRKT, NATIVE_SOL],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=ErGB9xa24Szxbk1M28u2Tx8rKPqzL6BroNkkzk5rG4zj&coin1=sol&fixed=coin0&ammId=H3dhkXcC5MRN7VRXNbWVSvogH8mUQPzpn8PYQL7HfBVg',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('15/11/2021'),
    tags: []
  },
  {
    symbol: 'WOOF-RAY',
    name: 'WOOF-RAY',
    coin: { ...TOKENS.WOOF },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.WOOF },

    mintAddress: 'H2FAnazDaGFutcmnrwDxhmdncR1Bd7GG4mhPCSUiamDX',
    decimals: TOKENS.WOOF.decimals,
    logos: [woofLogo, rayLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.WOOF, TOKENS.RAY],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=9nEqaUcb16sQ3Tn1psbkWqyhPdLmfHWjKGymREjsAgTE&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=3HYhQC6ne6SAPVT5sPTKawRUxv9ZpYyLuk1ifrw8baov',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('08/11/2021'),
    tags: []
  },
  {
    symbol: 'SYP-USDC',
    name: 'SYP-USDC',
    coin: { ...TOKENS.SYP },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SYP },

    mintAddress: '2xJGuLAivAR1WkARRA6zP1v4jaA9jV2Qis8JfMNvrVyZ',
    decimals: TOKENS.SYP.decimals,
    logos: [sypLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SYP, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=FnKE9n6aGjQoNWRBZXy4RW6LZVao7qwBonUbiD7edUmZ&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=2Tv6eMih3iqxHrLAWn372Nba4A8FT8AxFSbowBmmTuAd',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('03/11/2021'),
    tags: []
  },
  {
    symbol: 'SYP-RAY',
    name: 'SYP-RAY',
    coin: { ...TOKENS.SYP },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SYP },

    mintAddress: 'FT2KZqxxM8F2h9pZtTF4PyjK88bM4YbuBzd7ZPwQ5wMB',
    decimals: TOKENS.SYP.decimals,
    logos: [sypLogo, rayLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SYP, TOKENS.RAY],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=FnKE9n6aGjQoNWRBZXy4RW6LZVao7qwBonUbiD7edUmZ&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=3hhSfFhbk7Kd8XrRYKCcGAyUVYRaW9MLhcqAaU9kx6SA',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('03/11/2021'),
    tags: []
  },
  {
    symbol: 'SYP-SOL',
    name: 'SYP-SOL',
    coin: { ...TOKENS.SYP },
    pc: { ...NATIVE_SOL },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SYP },

    mintAddress: 'KHV6dfj2bDntzJ9z1S26cDfqWfUZdJRFmteLR6LxHwW',
    decimals: TOKENS.SYP.decimals,
    logos: [sypLogo, solLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SYP, NATIVE_SOL],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=FnKE9n6aGjQoNWRBZXy4RW6LZVao7qwBonUbiD7edUmZ&coin1=sol&fixed=coin0&ammId=D95EzH4ZsGLikvYzp7kmz1RM1xNMo1MXXiXaedQesA2m',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('03/11/2021'),
    tags: []
  },
  {
    symbol: 'LIQ-USDC',
    name: 'LIQ-USDC',
    coin: { ...TOKENS.LIQ },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.LIQ },

    mintAddress: 'GWpD3eTfhJB5KDCcnE85dBQrjAk2CsrgDF9b52R9CrjV',
    decimals: TOKENS.LIQ.decimals,
    logos: [liqLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.LIQ, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=4wjPQJ6PrkC4dHhYghwJzGBVP78DkBzA2U3kHoFNBuhj&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=33dWwj33J3NUzoTmkMAUq1VdXZL89qezxkdaHdN88vK2',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('02/11/2021'),
    tags: []
  },
  {
    symbol: 'LIQ-RAY',
    name: 'LIQ-RAY',
    coin: { ...TOKENS.LIQ },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.LIQ },

    mintAddress: '49YUsDrThJosHSagCn1F59Uc9NRxbr9thVrZikUnQDXy',
    decimals: TOKENS.LIQ.decimals,
    logos: [liqLogo, rayLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.LIQ, TOKENS.RAY],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=4wjPQJ6PrkC4dHhYghwJzGBVP78DkBzA2U3kHoFNBuhj&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=HuMDhYhW1BmBjXoJZBdjqaqoD3ehQeCUMbDSiZsaXSDU',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('02/11/2021'),
    tags: []
  },
  {
    symbol: 'MNDE-mSOL',
    name: 'MNDE-mSOL',
    coin: { ...TOKENS.MNDE },
    pc: { ...TOKENS.MSOLRAYDIUM },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MNDE },

    mintAddress: '4bh8XCzTHSbqbWN8o1Jn4ueBdz1LvJFoEasN6K6CQ8Ny',
    decimals: TOKENS.MNDE.decimals,
    logos: [mndeLogo, msolLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.MNDE, TOKENS.MSOLRAYDIUM],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey&coin1=sol&fixed=coin0',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('23/10/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'mSOL-USDC',
    name: 'mSOL-USDC',
    coin: { ...TOKENS.MSOLRAYDIUM },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MNDE },

    mintAddress: '4xTpJ4p76bAeggXoYywpCCNKfJspbuRzZ79R7pRhbqSf',
    decimals: TOKENS.MNDE.decimals,
    logos: [msolLogo, usdcLogo],
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.MSOLRAYDIUM, TOKENS.USDC],
    marginIndex: 31,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=ZfvDXXUhZDzDVsapffUyXHj9ByCoPjP4thL6YXcZ9ix',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('25/03/2022'),
    tags: []
  },
  {
    symbol: 'mSOL-USDT',
    name: 'mSOL-USDT',
    coin: { ...TOKENS.MSOLRAYDIUM },
    pc: { ...TOKENS.USDT },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MNDE },

    mintAddress: '69NCmEW9mGpiWLjAcAWHq51k4ionJZmzgRfRT3wQaCCf',
    decimals: TOKENS.MNDE.decimals,
    logos: [msolLogo, usdtLogo],
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.MSOLRAYDIUM, TOKENS.USDT],
    marginIndex: 32,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So&coin1=Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB&fixed=coin0&ammId=BhuMVCzwFVZMSuc1kBbdcAnXwFg9p4HJp7A9ddwYjsaF',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('25/03/2022'),
    tags: []
  },
  {
    symbol: 'mSOL-RAY',
    name: 'mSOL-RAY',
    coin: { ...TOKENS.MSOLRAYDIUM },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MNDE },

    mintAddress: 'De2EHBAdkgfc72DpShqDGG42cV3iDWh8wvvZdPsiEcqP',
    decimals: TOKENS.MNDE.decimals,
    logos: [msolLogo, rayLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.MSOLRAYDIUM, TOKENS.RAY],
    marginIndex: 35,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=6gpZ9JkLoYvpA5cwdyPZFsDw6tkbPyyXM5FqRqHxMCny',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('23/10/2021'),
    tags: [],
    isHiddenLeverageFarm: true,
    disabled: true
  },
  {
    symbol: 'ETH-mSOL',
    name: 'ETH-mSOL',
    coin: { ...TOKENS.ETH },
    pc: { ...TOKENS.MSOLRAYDIUM },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MNDE },

    mintAddress: 'HYv3grQfi8QbV7nG7EFgNK1aJSrsJ7HynXJKJVPLL2Uh',
    decimals: TOKENS.ETH.decimals,
    logos: [ethLogo, msolLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.ETH, TOKENS.MSOLRAYDIUM],
    marginIndex: 33,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=2FPyTwcZLUg1MDrwsyoP4D6s1tM7hAkHYRjkNb5w6Pxk&coin1=mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So&fixed=coin0&ammId=Ghj3v2qYbSp6XqmH4NV4KRu4Rrgqoh2Ra7L9jEdsbNzF',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('23/10/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'BTC-mSOL',
    name: 'BTC-mSOL',
    coin: { ...TOKENS.BTC },
    pc: { ...TOKENS.MSOLRAYDIUM },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MNDE },

    mintAddress: '92bcERNtUmuaJ6mwLSxYHZYSph37jdKxRdoYNxpcYNPp',
    decimals: TOKENS.BTC.decimals,
    logos: [btcLogo, msolLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.BTC, TOKENS.MSOLRAYDIUM],
    marginIndex: 34,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E&coin1=mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So&fixed=coin0&ammId=ynV2H2b7FcRBho2TvE25Zc4gDeuu2N45rUw9DuJYjJ9',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('23/10/2021'),
    tags: [],
    disabled: true
  },
  {
    symbol: 'LARIX-RAY',
    name: 'LARIX-RAY',
    coin: { ...TOKENS.LARIX },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.LARIX },

    mintAddress: 'ZRDfSLgWGeaYSmhdPvFNKQQhDcYdZQaue2N8YDmHX4q',
    decimals: TOKENS.LARIX.decimals,
    logos: [larixLogo, rayLogo],
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.LARIX, TOKENS.RAY],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=Lrxqnh6ZHKbGy3dcrCED43nsoLkM1LTzU2jRfWe8qUC&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=EBqQdu9rGe6j3WGJQSyTvDjUMWcRd6uLcxSS4TbFT31t',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    isNew: isFarmNew('16/10/2021'),
    tags: []
  },
  {
    symbol: 'LARIX-USDC',
    name: 'LARIX-USDC',
    coin: { ...TOKENS.LARIX },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.LARIX },

    mintAddress: '7yieit4YsNsZ9CAK8H5ZEMvvk35kPEHHeXwp6naoWU9V',
    decimals: TOKENS.LARIX.decimals,
    logos: [larixLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.LARIX, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 100000,
    link: 'https://raydium.io/liquidity/add/?coin0=Lrxqnh6ZHKbGy3dcrCED43nsoLkM1LTzU2jRfWe8qUC&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=A21ui9aYTSs3CbkscaY6irEMQx3Z59dLrRuZQTt2hJwQ',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    tags: []
  },
  {
    symbol: 'GRAPE-USDC',
    name: 'GRAPE-USDC',
    coin: { ...TOKENS.GRAPE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.GRAPE },

    mintAddress: 'A8ZYmnZ1vwxUa4wpJVUaJgegsuTEz5TKy5CiJXffvmpt',
    decimals: TOKENS.GRAPE.decimals,
    logos: [grapeLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.GRAPE, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 100000,
    link: 'https://raydium.io/liquidity/add/?coin0=8upjSpvjcdpuzhfR1zriwg5NXkwDruejqNE9WNbPRtyA&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=vVXfY15WdPsCmLvbiP4hWWECPFeAvPTuPNq3Q4BXfhy',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    tags: []
  },
  {
    symbol: 'ATLAS-USDC',
    name: 'ATLAS-USDC',
    coin: { ...TOKENS.ATLAS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.ATLAS },

    mintAddress: '9shGU9f1EsxAbiR567MYZ78WUiS6ZNCYbHe53WUULQ7n',
    decimals: TOKENS.ATLAS.decimals,
    logos: [atlasLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.ATLAS, TOKENS.USDC],
    marginIndex: 19,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=2bnZ1edbvK3CK3LTNZ5jH9anvXYCmzPR4W2HQ6Ngsv5K',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    tags: [],
    disabled: true
  },
  {
    symbol: 'POLIS-USDC',
    name: 'POLIS-USDC',
    coin: { ...TOKENS.POLIS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.POLIS },

    mintAddress: '8MbKSBpyXs8fVneKgt71jfHrn5SWtX8n4wMLpiVfF9So',
    decimals: TOKENS.POLIS.decimals,
    logos: [polisLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.POLIS, TOKENS.USDC],
    marginIndex: 21,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=9xyCzsHi1wUWva7t5Z8eAvZDRmUCVhRrbaFfm3VbU4Mf',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    tags: [],
    disabled: true
  },
  {
    symbol: 'ATLAS-RAY',
    name: 'ATLAS-RAY',
    coin: { ...TOKENS.ATLAS },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.ATLAS },

    mintAddress: '418MFhkaYQtbn529wmjLLqL6uKxDz7j4eZBaV1cobkyd',
    decimals: TOKENS.ATLAS.decimals,
    logos: [atlasLogo, rayLogo],
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.ATLAS, TOKENS.RAY],
    marginIndex: 20,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=F73euqPynBwrgcZn3fNSEneSnYasDQohPM5aZazW9hp2',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    tags: []
  },
  {
    symbol: 'POLIS-RAY',
    name: 'POLIS-RAY',
    coin: { ...TOKENS.POLIS },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.POLIS },

    mintAddress: '9ysGKUH6WqzjQEUT4dxqYCUaFNVK9QFEa24pGzjFq8xg',
    decimals: TOKENS.POLIS.decimals,
    logos: [polisLogo, rayLogo],
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.POLIS, TOKENS.RAY],
    marginIndex: 22,
    slippageWarning: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=5tho4By9RsqTF1rbm9Akiepik3kZBT7ffUzGg8bL1mD',
    rewardEndSlot: 93847628,
    platform: FARM_PLATFORMS.RAYDIUM,
    tags: []
  },
  {
    symbol: 'TULIP-USDC',
    name: 'TULIP-USDC',
    coin: { ...TOKENS.TULIP },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.TULIP },

    mintAddress: '2doeZGLJyACtaG9DCUyqMLtswesfje1hjNA11hMdj6YU',
    decimals: TOKENS.TULIP.decimals,
    logos: [tulipLogo, usdcLogo],
    dualYield: false,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.TULIP, TOKENS.USDC],
    marginIndex: 11,
    slippageWarning: true,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=TuLipcqtGVXP9XR62wM8WWCm6a9vhLs7T1uoWBk6FDs&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=96hPvuJ3SRT82m7BAc7G1AUVPVcoj8DABAa5gT7wjgzX',
    rewardEndSlot: 93847628,
    disabled: true,
    tags: []
  },
  {
    symbol: 'RAY',
    name: 'Raydium',
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
    decimals: 6,
    referrer: '33XpMmMQRf6tSPpmYyzpwU4uXpZHkFwCZsusD9dMYkjy',
    logos: [rayLogo, emptyLogo],
    singleStake: true,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.RAY, TOKENS.RAY],
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/staking/',
    rewardEndSlot: 94284986,
    tags: []
  },
  {
    symbol: 'RAY-USDT',
    name: 'RAY-USDT',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.USDT },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: 'C3sT1R3nsw4AVdepvLTLKr5Gvszr7jufyBWUCvy4TUvT',
    decimals: TOKENS.RAY.decimals,
    logos: [rayLogo, usdtLogo],
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.RAY, TOKENS.USDT],
    marginIndex: 2,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&coin1=Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB&fixed=coin0&ammId=DVa7Qmb5ct9RCpaU7UTpSaf3GVMYz17vNVU67XpdCRut',
    rewardEndSlot: 94284901,
    tags: []
  },
  {
    symbol: 'RAY-USDC',
    name: 'RAY-USDC',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: 'FbC6K13MzHvN42bXrtGaWsvZY9fxrackRSZcBGfjPc7m',
    decimals: TOKENS.RAY.decimals,
    logos: [rayLogo, usdcLogo],
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.RAY, TOKENS.USDC],
    marginIndex: 0,
    whitelisted: false,
    disabled: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg',
    migrated: true,
    rewardEndSlot: 94285165,
    tags: []
  },
  {
    symbol: 'RAY-SRM',
    name: 'RAY-SRM',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.SRM },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: '7P5Thr9Egi2rvMmEuQkLn8x8e8Qro7u2U7yLD2tU2Hbe',
    decimals: TOKENS.RAY.decimals,
    logos: [rayLogo, srmLogo],
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.RAY, TOKENS.SRM],
    marginIndex: 3,
    whitelisted: false,
    disabled: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&coin1=SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt&fixed=coin0&ammId=GaqgfieVmnmY4ZsZHHA6L5RSVzCGL3sKx4UgHBaYNy8m',
    migrated: true,
    rewardEndSlot: 94284925,
    tags: []
  },
  {
    symbol: 'RAY-SOL',
    name: 'RAY-SOL',
    coin: { ...TOKENS.RAY },
    pc: { ...NATIVE_SOL },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: '89ZKE4aoyfLBe2RuV6jM3JGNhaV18Nxh8eNtjRcndBip',
    decimals: TOKENS.RAY.decimals,
    logos: [rayLogo, solLogo],
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.RAY, NATIVE_SOL],
    marginIndex: 1,
    whitelisted: false,
    disabled: false,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&coin1=sol&fixed=coin0&ammId=AVs9TA4nWDzfPJE9gGVNJMVhcQy3V9PGazuz33BfG2RA',
    migrated: true,
    rewardEndSlot: 94284942,
    tags: []
  },
  {
    symbol: 'RAY-ETH',
    name: 'RAY-ETH',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.ETH },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.RAY },

    mintAddress: 'mjQH33MqZv5aKAbKHi8dG3g3qXeRQqq1GFcXceZkNSr',
    decimals: TOKENS.RAY.decimals,
    logos: [rayLogo, ethLogo],
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.RAY, TOKENS.ETH],
    whitelisted: false,
    disabled: false,
    marginIndex: 7,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&coin1=2FPyTwcZLUg1MDrwsyoP4D6s1tM7hAkHYRjkNb5w6Pxk&fixed=coin0&ammId=8iQFhWyceGREsWnLM8NkG9GC8DvZunGZyMzuyUScgkMK',
    migrated: true,
    rewardEndSlot: 94284954,
    tags: []
  },
  {
    symbol: 'MEDIA-USDC',
    name: 'MEDIA-USDC',
    coin: { ...TOKENS.MEDIA },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MEDIA },

    mintAddress: 'A5zanvgtioZGiJMdEyaKN4XQmJsp1p7uVxaq2696REvQ',
    decimals: TOKENS.MEDIA.decimals,
    logos: [mediaLogo, usdcLogo],
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.MEDIA, TOKENS.USDC],
    marginIndex: 5,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=ETAtLmCmsoiEEKfNrHKJ2kYy3MoABhU6NQvpSfij5tDs&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=94CQopiGxxUXf2avyMZhAFaBdNatd62ttYGoTVQBRGdi',
    rewardEndSlot: 94284801,
    disabled: true,
    tags: []
  },
  {
    symbol: 'SAMO-RAY',
    name: 'SAMO-RAY',
    coin: { ...TOKENS.SAMO },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SAMO },

    mintAddress: 'HwzkXyX8B45LsaHXwY8su92NoRBS5GQC32HzjQRDqPnr',
    decimals: TOKENS.SAMO.decimals,
    logos: [samoLogo, rayLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.SAMO, TOKENS.RAY],
    link: 'https://raydium.io/liquidity/add/?coin0=7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=EyDgEU9BdG7m6ZK4bYERxbN4NCJ129WzPtv23dBkfsLg',
    rewardEndSlot: 93040503,
    marginIndex: 36,
    tags: []
  },
  {
    symbol: 'COPE-USDC',
    name: 'COPE-USDC',
    coin: { ...TOKENS.COPE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.COPE },

    mintAddress: 'Cz1kUvHw98imKkrqqu95GQB9h1frY8RikxPojMwWKGXf',
    decimals: TOKENS.COPE.decimals,
    logos: [copeLogo, usdcLogo],
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.COPE, TOKENS.USDC],
    marginIndex: 6,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=8HGyAAB1yoM1ttS7pXjHMa3dukTFGQggnFFH3hJZgzQh&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=DiWxV1SPXPNJRCt5Ao1mJRAxjw97hJVyj8qGzZwFbAFb',
    slippageWarning: true,
    rewardEndSlot: 94284813,
    tags: [],
    disabled: true
  },
  {
    symbol: 'MER-USDC',
    name: 'MER-USDC',
    coin: { ...TOKENS.MER },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MER },

    mintAddress: '3H9NxvaZoxMZZDZcbBDdWMKbrfNj7PCF5sbRwDr7SdDW',
    decimals: TOKENS.MER.decimals,
    logos: [merLogo, usdcLogo],
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.MER, TOKENS.USDC],
    marginIndex: 4,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=MERt85fc5boKw3BW1eYdxonEuJNvXbiMbs6hvheau5K&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=BkfGDk676QFtTiGxn7TtEpHayJZRr6LgNk9uTV2MH4bR',
    rewardEndSlot: 94284972,
    tags: [],
    disabled: true
  },
  {
    symbol: 'ALEPH-USDC',
    name: 'ALEPH-USDC',
    coin: { ...TOKENS.ALEPH },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.ALEPH },

    mintAddress: 'iUDasAP2nXm5wvTukAHEKSdSXn8vQkRtaiShs9ceGB7',
    decimals: TOKENS.ALEPH.decimals,
    logos: [alephLogo, usdcLogo],
    dualYield: false,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.ALEPH, TOKENS.USDC],
    marginIndex: 10,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=CsZ5LZkDS7h9TDKjrbL7VAwQZ9nsRu8vJLhRYfmGaN8K&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=GDHXjn9wF2zxW35DBkCegWQdoTfFBC9LXt7D5ovJxQ5B',
    slippageWarning: true,
    rewardEndSlot: 94134929,
    tags: [],
    highLiquidity: true,
    disabled: true
  },
  {
    symbol: 'LIKE-USDC',
    name: 'LIKE-USDC',
    coin: { ...TOKENS.LIKE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.LIKE },

    mintAddress: 'cjZmbt8sJgaoyWYUttomAu5LJYU44ZrcKTbzTSEPDVw',
    decimals: TOKENS.LIKE.decimals,
    logos: [likeLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.LIKE, TOKENS.USDC],
    marginIndex: 16,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=3bRTivrVsitbmCTGtqwp7hxXPsybkjn4XLNtPsHqa3zR&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=GmaDNMWsTYWjaXVBjJTHNmCWAKU6cn5hhtWWYEZt4odo',
    rewardEndSlot: 93040503,
    tags: []
  },
  {
    symbol: 'KIN-RAY',
    name: 'KIN-RAY',
    coin: { ...TOKENS.KIN },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.KIN },

    mintAddress: 'CHT8sft3h3gpLYbCcZ9o27mT5s3Z6VifBVbUiDvprHPW',
    decimals: 6,
    logos: [kinLogo, rayLogo],
    dualYield: true,
    liquidityMining: true,
    totalTulipEmission: 0,
    disabled: false,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.KIN, TOKENS.RAY],
    link: 'https://raydium.io/liquidity/add/?coin0=kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=6kmMMacvoCKBkBrqssLEdFuEZu2wqtLdNQxh9VjtzfwT',
    rewardEndSlot: 93040503,
    isNew: isFarmNew('15/11/2021'),
    tags: []
  },
  {
    symbol: 'BOP-RAY',
    name: 'BOP-RAY',
    coin: { ...TOKENS.BOP },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.BOP },

    mintAddress: '9nQPYJvysyfnXhQ6nkK5V7sZG26hmDgusfdNQijRk5LD',
    decimals: TOKENS.BOP.decimals,
    logos: [bopLogo, rayLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.BOP, TOKENS.RAY],
    link: 'https://raydium.io/liquidity/add/?coin0=BLwTnYKqf7u4qjgZrrsKeNs2EzWkMLqVCu6j8iHyrNA3&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=SJmR8rJgzzCi4sPjGnrNsqY4akQb3jn5nsxZBhyEifC',
    rewardEndSlot: 93040503,
    tags: []
  },
  {
    symbol: 'ROPE-USDC',
    name: 'ROPE-USDC',
    coin: { ...TOKENS.ROPE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.ROPE },

    mintAddress: 'Cq4HyW5xia37tKejPF2XfZeXQoPYW6KfbPvxvw5eRoUE',
    decimals: TOKENS.ROPE.decimals,
    logos: [ropeLogo, usdcLogo],
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.ROPE, TOKENS.USDC],
    marginIndex: 9,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=8PMHT4swUMtBzgHnh5U564N5sjPSiUz2cjEQzFnnP1Fo&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=BuS4ScFcZjEBixF1ceCTiXs4rqt4WDfXLoth7VcM2Eoj',
    rewardEndSlot: 94284962,
    tags: [],
    disabled: true
  },
  {
    symbol: 'SNY-USDC',
    name: 'SNY-USDC',
    coin: { ...TOKENS.SNY },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SNY },

    mintAddress: 'G8qcfeFqxwbCqpxv5LpLWxUCd1PyMB5nWb5e5YyxLMKg',
    decimals: TOKENS.SNY.decimals,
    logos: [snyLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.SNY, TOKENS.USDC],
    marginIndex: 12,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=4dmKkXNHdgYsXqBHCuMikNQWwVomZURhYvkkX5c4pQ7y&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=5TgJXpv6H3KJhHCuP7KoDLSCmi8sM8nABizP7CmYAKm1',
    slippageWarning: true,
    rewardEndSlot: 93252854,
    disabled: true,
    isNew: isFarmNew('05/02/2022'),
    tags: []
  },
  {
    symbol: 'SLRS-USDC',
    name: 'SLRS-USDC',
    coin: { ...TOKENS.SLRS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SLRS },

    mintAddress: '2Xxbm1hdv5wPeen5ponDSMT3VqhGMTQ7mH9stNXm9shU',
    decimals: TOKENS.SLRS.decimals,
    logos: [slrsLogo, usdcLogo],
    dualYield: false,
    liquidityMining: true,
    totalTulipEmission: 0, // 450000 / 810
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.SLRS, TOKENS.USDC],
    marginIndex: 14,
    slippageWarning: true,
    maxPositionLimitInUsd: 9000000,
    link: 'https://raydium.io/liquidity/add/?coin0=SLRSSpSLUTP7okbCUBYStWCo1vUgyt775faPqz8HUMr&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=7XXKU8oGDbeGrkPyK5yHKzdsrMJtB7J2TMugjbrXEhB5',
    rewardEndSlot: 93040503,
    disabled: true,
    tags: []
  },
  {
    symbol: 'MNGO-USDC',
    name: 'MNGO-USDC',
    coin: { ...TOKENS.MNGO },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MNGO },

    mintAddress: 'DkiqCQ792n743xjWQVCbBUaVtkdiuvQeYndM53ReWnCC',
    decimals: TOKENS.MNGO.decimals,
    logos: [mngoLogo, usdcLogo],
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    disabled: true,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.MNGO, TOKENS.USDC],
    marginIndex: 200,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=34tFULRrRwh4bMcBLPtJaNqqe5pVgGZACi5sR8Xz95KC',
    rewardEndSlot: 93040503,
    tags: []
  },
  {
    symbol: 'RAY-SRM-DUAL',
    name: 'RAY-SRM',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.SRM },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },

    mintAddress: '7P5Thr9Egi2rvMmEuQkLn8x8e8Qro7u2U7yLD2tU2Hbe',
    decimals: TOKENS.RAY.decimals,
    logos: [rayLogo, srmLogo],
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.RAY, TOKENS.SRM],
    marginIndex: 666,
    whitelisted: false,
    disabled: true,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&coin1=SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt&fixed=coin0&ammId=GaqgfieVmnmY4ZsZHHA6L5RSVzCGL3sKx4UgHBaYNy8m',
    migrated: false,
    dualYield: true,
    rewardEndSlot: 0,
    hidden: true,
    tags: []
  },
  {
    symbol: 'STEP-USDC',
    name: 'STEP-USDC',
    coin: { ...TOKENS.STEP },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.STEP },

    mintAddress: '3k8BDobgihmk72jVmXYLE168bxxQUhqqyESW4dQVktqC',
    decimals: TOKENS.STEP.decimals,
    logos: [stepLogo, usdcLogo],
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.STEP, TOKENS.USDC],
    marginIndex: 8,
    disabled: true,
    maxPositionLimitInUsd: 0,
    link: 'https://raydium.io/liquidity/add/?coin0=StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT&coin1=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&fixed=coin0&ammId=4Sx1NLrQiK4b9FdLKe2DhQ9FHvRzJhzKN3LoD6BrEPnf',
    rewardEndSlot: 94285155,
    tags: []
  },
  {
    symbol: 'FIDA-RAY',
    name: 'FIDA-RAY',
    coin: { ...TOKENS.FIDA },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.FIDA },

    mintAddress: 'DsBuznXRTmzvEdb36Dx3aVLVo1XmH7r1PRZUFugLPTFv',
    decimals: TOKENS.FIDA.decimals,
    logos: [fidaLogo, rayLogo],
    dualYield: true,
    liquidityMining: true,
    totalTulipEmission: 0,
    disabled: true,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.FIDA, TOKENS.RAY],
    link: 'https://raydium.io/liquidity/add/?coin0=EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=2dRNngAm729NzLbb1pzgHtfHvPqR4XHFmFyYK78EfEeX',
    rewardEndSlot: 93040503,
    tags: []
  },
  {
    symbol: 'OXY-RAY',
    name: 'OXY-RAY',
    coin: { ...TOKENS.OXY },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.OXY },

    mintAddress: 'FwaX9W7iThTZH5MFeasxdLpxTVxRcM7ZHieTCnYog8Yb',
    decimals: TOKENS.OXY.decimals,
    logos: [oxyLogo, rayLogo],
    dualYield: true,
    liquidityMining: true,
    totalTulipEmission: 0,
    disabled: true,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.OXY, TOKENS.RAY],
    link: 'https://raydium.io/liquidity/add/?coin0=z3dn17yLaGMKffVogeFHQ9zWVcXgqgf3PQnDsNs2g6M&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=B5ZguAWAGC3GXVtJZVfoMtzvEvDnDKBPCevsUKMy4DTZ',
    rewardEndSlot: 93040503,
    tags: []
  },
  {
    symbol: 'MAPS-RAY',
    name: 'MAPS-RAY',
    coin: { ...TOKENS.MAPS },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MAPS },

    mintAddress: 'CcKK8srfVdTSsFGV3VLBb2YDbzF4T4NM2C3UEjC39RLP',
    decimals: TOKENS.MAPS.decimals,
    logos: [mapsLogo, rayLogo],
    dualYield: true,
    liquidityMining: true,
    totalTulipEmission: 0,
    disabled: true,
    saber: false,
    platform: FARM_PLATFORMS.RAYDIUM,
    coins: [TOKENS.MAPS, TOKENS.RAY],
    link: 'https://raydium.io/liquidity/add/?coin0=MAPS41MDahZ9QdKXhVa4dWB9RuyfV4XqhyAZ8XcYepb&coin1=4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R&fixed=coin0&ammId=5VyLSjUvaRxsubirbvbfJMbrKZRx1b7JZzuCAfyqgimf',
    rewardEndSlot: 93040503,
    tags: []
  }
];

export const FARM_PLATFORMS = {
  RAYDIUM: 'raydium',
  SABER: 'saber',
  ORCA: 'orca',
  TULIP: 'tulip',
  SOLEND: 'solend',
  MANGO: 'mango'
};
