import { NATIVE_SOL, TOKENS } from './tokens';

export const FARMS = [
  {
    symbol: 'GRAPE-USDC',
    name: 'GRAPE-USDC LP',
    coin: { ...TOKENS.GRAPE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.GRAPE },

    mintAddress: 'A8ZYmnZ1vwxUa4wpJVUaJgegsuTEz5TKy5CiJXffvmpt',
    decimals: TOKENS.GRAPE.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.GRAPE, TOKENS.USDC],
    marginIndex: 1111,
    slippageWarning: false,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 93847628
  },
  {
    symbol: 'ATLAS-USDC',
    name: 'ATLAS-USDC LP',
    coin: { ...TOKENS.ATLAS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.ATLAS },

    mintAddress: '9shGU9f1EsxAbiR567MYZ78WUiS6ZNCYbHe53WUULQ7n',
    decimals: TOKENS.ATLAS.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.ATLAS, TOKENS.USDC],
    marginIndex: 19,
    slippageWarning: false,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 93847628
  },
  {
    symbol: 'POLIS-USDC',
    name: 'POLIS-USDC LP',
    coin: { ...TOKENS.POLIS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.POLIS },

    mintAddress: '8MbKSBpyXs8fVneKgt71jfHrn5SWtX8n4wMLpiVfF9So',
    decimals: TOKENS.POLIS.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.POLIS, TOKENS.USDC],
    marginIndex: 21,
    slippageWarning: false,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 93847628
  },
  {
    symbol: 'ATLAS-RAY',
    name: 'ATLAS-RAY LP',
    coin: { ...TOKENS.ATLAS },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.ATLAS },

    mintAddress: '418MFhkaYQtbn529wmjLLqL6uKxDz7j4eZBaV1cobkyd',
    decimals: TOKENS.ATLAS.decimals,
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.ATLAS, TOKENS.RAY],
    marginIndex: 20,
    slippageWarning: false,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 93847628
  },
  {
    symbol: 'POLIS-RAY',
    name: 'POLIS-RAY LP',
    coin: { ...TOKENS.POLIS },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.POLIS },

    mintAddress: '9ysGKUH6WqzjQEUT4dxqYCUaFNVK9QFEa24pGzjFq8xg',
    decimals: TOKENS.POLIS.decimals,
    dualYield: true,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.POLIS, TOKENS.RAY],
    marginIndex: 22,
    slippageWarning: false,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 93847628
  },
  {
    symbol: 'TULIP-USDC',
    name: 'TULIP-USDC LP',
    coin: { ...TOKENS.TULIP },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.TULIP },

    mintAddress: '2doeZGLJyACtaG9DCUyqMLtswesfje1hjNA11hMdj6YU',
    decimals: TOKENS.TULIP.decimals,
    dualYield: false,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    coins: [TOKENS.TULIP, TOKENS.USDC],
    marginIndex: 11,
    slippageWarning: true,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 93847628
  },
  {
    symbol: 'RAY',
    name: 'Raydium',
    reward: { ...TOKENS.RAY },

    mintAddress: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
    decimals: 6,
    referrer: '33XpMmMQRf6tSPpmYyzpwU4uXpZHkFwCZsusD9dMYkjy',
    singleStake: true,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    coins: [TOKENS.RAY, TOKENS.RAY],
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 94284986
  },
  {
    symbol: 'RAY-USDT',
    name: 'RAY-USDT LP',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.USDT },
    reward: { ...TOKENS.RAY },

    mintAddress: 'C3sT1R3nsw4AVdepvLTLKr5Gvszr7jufyBWUCvy4TUvT',
    decimals: TOKENS.RAY.decimals,
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    coins: [TOKENS.RAY, TOKENS.USDT],
    marginIndex: 2,
    maxPositionLimitInUsd: 300000,
    rewardEndSlot: 94284901
  },
  {
    symbol: 'RAY-USDC',
    name: 'RAY-USDC LP',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },

    mintAddress: 'FbC6K13MzHvN42bXrtGaWsvZY9fxrackRSZcBGfjPc7m',
    decimals: TOKENS.RAY.decimals,
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    coins: [TOKENS.RAY, TOKENS.USDC],
    marginIndex: 0,
    whitelisted: false,
    disabled: false,
    maxPositionLimitInUsd: 300000,
    migrated: true,
    rewardEndSlot: 94285165
  },
  {
    symbol: 'RAY-SRM',
    name: 'RAY-SRM LP',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.SRM },
    reward: { ...TOKENS.RAY },

    mintAddress: '7P5Thr9Egi2rvMmEuQkLn8x8e8Qro7u2U7yLD2tU2Hbe',
    decimals: TOKENS.RAY.decimals,
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    coins: [TOKENS.RAY, TOKENS.SRM],
    marginIndex: 3,
    whitelisted: false,
    disabled: false,
    maxPositionLimitInUsd: 300000,
    migrated: true,
    rewardEndSlot: 94284925
  },
  {
    symbol: 'RAY-SOL',
    name: 'RAY-SOL LP',
    coin: { ...TOKENS.RAY },
    pc: { ...NATIVE_SOL },
    reward: { ...TOKENS.RAY },

    mintAddress: '89ZKE4aoyfLBe2RuV6jM3JGNhaV18Nxh8eNtjRcndBip',
    decimals: TOKENS.RAY.decimals,
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    coins: [TOKENS.RAY, NATIVE_SOL],
    marginIndex: 1,
    whitelisted: false,
    disabled: false,
    maxPositionLimitInUsd: 300000,
    migrated: true,
    rewardEndSlot: 94284942
  },
  {
    symbol: 'RAY-ETH',
    name: 'RAY-ETH LP',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.ETH },
    reward: { ...TOKENS.RAY },

    mintAddress: 'mjQH33MqZv5aKAbKHi8dG3g3qXeRQqq1GFcXceZkNSr',
    decimals: TOKENS.RAY.decimals,
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    coins: [TOKENS.RAY, TOKENS.ETH],
    whitelisted: false,
    disabled: false,
    marginIndex: 7,
    maxPositionLimitInUsd: 300000,
    migrated: true,
    rewardEndSlot: 94284954
  },
  {
    symbol: 'MEDIA-USDC',
    name: 'MEDIA-USDC LP',
    coin: { ...TOKENS.MEDIA },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MEDIA },

    mintAddress: 'A5zanvgtioZGiJMdEyaKN4XQmJsp1p7uVxaq2696REvQ',
    decimals: TOKENS.MEDIA.decimals,
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    coins: [TOKENS.MEDIA, TOKENS.USDC],
    marginIndex: 5,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 94284801
  },
  {
    symbol: 'COPE-USDC',
    name: 'COPE-USDC LP',
    coin: { ...TOKENS.COPE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.COPE },

    mintAddress: 'Cz1kUvHw98imKkrqqu95GQB9h1frY8RikxPojMwWKGXf',
    decimals: TOKENS.COPE.decimals,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    coins: [TOKENS.COPE, TOKENS.USDC],
    marginIndex: 6,
    maxPositionLimitInUsd: 100000,
    slippageWarning: true,
    rewardEndSlot: 94284813
  },
  {
    symbol: 'MER-USDC',
    name: 'MER-USDC LP',
    coin: { ...TOKENS.MER },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MER },

    mintAddress: '3H9NxvaZoxMZZDZcbBDdWMKbrfNj7PCF5sbRwDr7SdDW',
    decimals: TOKENS.MER.decimals,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    coins: [TOKENS.MER, TOKENS.USDC],
    marginIndex: 4,
    maxPositionLimitInUsd: 0,
    rewardEndSlot: 94284972
  },
  {
    symbol: 'ROPE-USDC',
    name: 'ROPE-USDC LP',
    coin: { ...TOKENS.ROPE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.ROPE },

    mintAddress: 'Cq4HyW5xia37tKejPF2XfZeXQoPYW6KfbPvxvw5eRoUE',
    decimals: TOKENS.ROPE.decimals,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    coins: [TOKENS.ROPE, TOKENS.USDC],
    marginIndex: 9,
    maxPositionLimitInUsd: 0,
    rewardEndSlot: 94284962
  },
  {
    symbol: 'ALEPH-USDC',
    name: 'ALEPH-USDC LP',
    coin: { ...TOKENS.ALEPH },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.ALEPH },

    mintAddress: 'iUDasAP2nXm5wvTukAHEKSdSXn8vQkRtaiShs9ceGB7',
    decimals: TOKENS.ALEPH.decimals,
    dualYield: false,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    coins: [TOKENS.ALEPH, TOKENS.USDC],
    marginIndex: 10,
    maxPositionLimitInUsd: 100000,
    slippageWarning: true,
    rewardEndSlot: 94134929
  },
  {
    symbol: 'SNY-USDC',
    name: 'SNY-USDC LP',
    coin: { ...TOKENS.SNY },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SNY },

    mintAddress: 'G8qcfeFqxwbCqpxv5LpLWxUCd1PyMB5nWb5e5YyxLMKg',
    decimals: TOKENS.SNY.decimals,
    dualYield: false,
    liquidityMining: true,
    totalTulipEmission: 450000 / 810,
    saber: false,
    coins: [TOKENS.SNY, TOKENS.USDC],
    marginIndex: 12,
    maxPositionLimitInUsd: 100000,
    slippageWarning: true,
    rewardEndSlot: 93252854
  },
  {
    symbol: 'SLRS-USDC',
    name: 'SLRS-USDC LP',
    coin: { ...TOKENS.SLRS },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SLRS },

    mintAddress: '2Xxbm1hdv5wPeen5ponDSMT3VqhGMTQ7mH9stNXm9shU',
    decimals: TOKENS.SLRS.decimals,
    dualYield: false,
    liquidityMining: true,
    totalTulipEmission: 0, // 450000 / 810
    saber: false,
    coins: [TOKENS.SLRS, TOKENS.USDC],
    marginIndex: 14,
    slippageWarning: true,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 93040503
  },
  {
    symbol: 'MNGO-USDC',
    name: 'MNGO-USDC LP',
    coin: { ...TOKENS.MNGO },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MNGO },

    mintAddress: 'DkiqCQ792n743xjWQVCbBUaVtkdiuvQeYndM53ReWnCC',
    decimals: TOKENS.MNGO.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.MNGO, TOKENS.USDC],
    marginIndex: 200,
    maxPositionLimitInUsd: 0,
    rewardEndSlot: 93040503
  },
  {
    symbol: 'LIKE-USDC',
    name: 'LIKE-USDC LP',
    coin: { ...TOKENS.LIKE },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.LIKE },

    mintAddress: 'cjZmbt8sJgaoyWYUttomAu5LJYU44ZrcKTbzTSEPDVw',
    decimals: TOKENS.LIKE.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.LIKE, TOKENS.USDC],
    marginIndex: 16,
    maxPositionLimitInUsd: 100000,
    rewardEndSlot: 93040503
  },
  {
    symbol: 'BOP-RAY',
    name: 'BOP-RAY LP',
    coin: { ...TOKENS.BOP },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.BOP },

    mintAddress: '9nQPYJvysyfnXhQ6nkK5V7sZG26hmDgusfdNQijRk5LD',
    decimals: TOKENS.BOP.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.BOP, TOKENS.RAY],
    rewardEndSlot: 93040503
  },
  {
    symbol: 'SAMO-RAY',
    name: 'SAMO-RAY LP',
    coin: { ...TOKENS.SAMO },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SAMO },

    mintAddress: 'HwzkXyX8B45LsaHXwY8su92NoRBS5GQC32HzjQRDqPnr',
    decimals: TOKENS.SAMO.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.SAMO, TOKENS.RAY],
    rewardEndSlot: 93040503
  },
  {
    symbol: 'RAY-SRM-DUAL',
    name: 'RAY-SRM LP',
    coin: { ...TOKENS.RAY },
    pc: { ...TOKENS.SRM },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.SRM },

    mintAddress: '7P5Thr9Egi2rvMmEuQkLn8x8e8Qro7u2U7yLD2tU2Hbe',
    decimals: TOKENS.RAY.decimals,
    liquidityMining: false,
    totalTulipEmission: 0,
    saber: false,
    coins: [TOKENS.RAY, TOKENS.SRM],
    marginIndex: 666,
    whitelisted: false,
    disabled: true,
    maxPositionLimitInUsd: 0,
    migrated: false,
    dualYield: true,
    rewardEndSlot: 0
  },
  {
    symbol: 'STEP-USDC',
    name: 'STEP-USDC LP',
    coin: { ...TOKENS.STEP },
    pc: { ...TOKENS.USDC },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.STEP },

    mintAddress: '3k8BDobgihmk72jVmXYLE168bxxQUhqqyESW4dQVktqC',
    decimals: TOKENS.STEP.decimals,
    liquidityMining: true,
    totalTulipEmission: 750000 / 630,
    saber: false,
    coins: [TOKENS.STEP, TOKENS.USDC],
    marginIndex: 8,
    disabled: true,
    maxPositionLimitInUsd: 0,
    rewardEndSlot: 94285155
  },
  {
    symbol: 'KIN-RAY',
    name: 'KIN-RAY LP',
    coin: { ...TOKENS.KIN },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.KIN },

    mintAddress: 'CHT8sft3h3gpLYbCcZ9o27mT5s3Z6VifBVbUiDvprHPW',
    decimals: 6,
    dualYield: true,
    liquidityMining: true,
    totalTulipEmission: 0,
    disabled: true,
    saber: false,
    coins: [TOKENS.KIN, TOKENS.RAY],
    rewardEndSlot: 93040503
  },
  {
    symbol: 'FIDA-RAY',
    name: 'FIDA-RAY LP',
    coin: { ...TOKENS.FIDA },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.FIDA },

    mintAddress: 'DsBuznXRTmzvEdb36Dx3aVLVo1XmH7r1PRZUFugLPTFv',
    decimals: TOKENS.FIDA.decimals,
    dualYield: true,
    liquidityMining: true,
    totalTulipEmission: 0,
    disabled: true,
    saber: false,
    coins: [TOKENS.FIDA, TOKENS.RAY],
    rewardEndSlot: 93040503
  },
  {
    symbol: 'OXY-RAY',
    name: 'OXY-RAY LP',
    coin: { ...TOKENS.OXY },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.OXY },

    mintAddress: 'FwaX9W7iThTZH5MFeasxdLpxTVxRcM7ZHieTCnYog8Yb',
    decimals: TOKENS.OXY.decimals,
    dualYield: true,
    liquidityMining: true,
    totalTulipEmission: 0,
    disabled: true,
    saber: false,
    coins: [TOKENS.OXY, TOKENS.RAY],
    rewardEndSlot: 93040503
  },
  {
    symbol: 'MAPS-RAY',
    name: 'MAPS-RAY LP',
    coin: { ...TOKENS.MAPS },
    pc: { ...TOKENS.RAY },
    reward: { ...TOKENS.RAY },
    rewardB: { ...TOKENS.MAPS },

    mintAddress: 'CcKK8srfVdTSsFGV3VLBb2YDbzF4T4NM2C3UEjC39RLP',
    decimals: TOKENS.MAPS.decimals,
    dualYield: true,
    liquidityMining: true,
    totalTulipEmission: 0,
    disabled: true,
    saber: false,
    coins: [TOKENS.MAPS, TOKENS.RAY],
    rewardEndSlot: 93040503
  }
];
