import { TOKENS } from './tokens';
import { FARM_PLATFORMS } from './farms';

export const SABER_VAULTS = [
  {
    symbol: 'UXD-USDC',
    name: 'UXD-USDC LP',
    coin: { ...TOKENS.UXD },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.UXD, TOKENS.USDC],
    reward: { ...TOKENS.SBR },
    rewardB: { ...TOKENS.SUNNY },
    mintAddress: 'UXDgmqLd1roNYkC4TmJzok61qcM9oKs5foDADiFoCiJ',
    decimals: TOKENS.UXD.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.SABER,
    sunnyPlatform: 'SunnyxSaber',
    link: 'https://app.saber.so/#/pools/uxd/deposit',
    totalSBREmission: 22000,
    totalSunnyEmission: 1610000
  },
  {
    symbol: 'CASH-USDC',
    name: 'CASH-USDC LP',
    coin: { ...TOKENS.CASH },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.CASH, TOKENS.USDC],
    reward: { ...TOKENS.SBR },
    rewardB: { ...TOKENS.SUNNY },
    mintAddress: 'CLPKiHjoU5HwpPK5L6MBXHKqFsuzPr47dM1w4An3Lnvv',
    decimals: TOKENS.CASH.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.SABER,
    sunnyPlatform: 'SunnyxSaber',
    link: 'https://app.saber.so/#/pools/cash/deposit',
    totalSBREmission: 22000,
    totalSunnyEmission: 790000
  },
  {
    symbol: 'USDC-USDT',
    name: 'USDT-USDC LP',
    coin: { ...TOKENS.USDC },
    pc: { ...TOKENS.USDT },
    coins: [TOKENS.USDC, TOKENS.USDT],
    reward: { ...TOKENS.SBR },
    rewardB: { ...TOKENS.SUNNY },
    mintAddress: '2poo1w1DL6yd2WNTCnNTzDqkC6MBXq7axo77P16yrBuf',
    decimals: TOKENS.USDC.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.SABER,
    sunnyPlatform: 'SunnyxSaber',
    link: 'https://app.saber.so/#/pools/usdc_usdt/deposit',
    totalSBREmission: 400000,
    totalSunnyEmission: 1750000
  },
  {
    symbol: 'UST-USDC',
    name: 'UST-USDC LP',
    coin: { ...TOKENS.wUST },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.wUST, TOKENS.USDC],
    reward: { ...TOKENS.SBR },
    rewardB: { ...TOKENS.SUNNY },
    mintAddress: 'USTCmQpbUGj5iTsXdnTYHZupY1QpftDZhLokSVk6UWi',
    decimals: TOKENS.wUST.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.SABER,
    sunnyPlatform: 'SunnyxSaber',
    link: 'https://app.saber.so/#/pools/wust/deposit',
    totalSBREmission: 250000,
    totalSunnyEmission: 200000
  },
  {
    symbol: 'mSOL-SOL',
    name: 'mSOL-SOL LP',
    coin: { ...TOKENS.MSOL },
    pc: { ...TOKENS.WSOL },
    coins: [TOKENS.MSOL, TOKENS.WSOL],
    reward: { ...TOKENS.SBR },
    rewardB: { ...TOKENS.SUNNY },
    mintAddress: 'SoLEao8wTzSfqhuou8rcYsVoLjthVmiXuEjzdNPMnCz',
    decimals: TOKENS.MSOL.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.SABER,
    sunnyPlatform: 'SunnyxSaber',
    link: 'https://app.saber.so/#/pools/msol_sol/deposit',
    totalSBREmission: 62000,
    totalSunnyEmission: 50000
  },
  {
    symbol: 'daoSOL-SOL',
    name: 'daoSOL-SOL LP',
    coin: { ...TOKENS.daoSOL },
    pc: { ...TOKENS.WSOL },
    coins: [TOKENS.daoSOL, TOKENS.WSOL],
    reward: { ...TOKENS.SBR },
    rewardB: { ...TOKENS.SUNNY },
    mintAddress: 'monKYjV2bHTjbJVWCCcwhxE8C96sdTKR2HUNUHCjh4z',
    decimals: TOKENS.daoSOL.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.SABER,
    sunnyPlatform: 'SunnyxSaber',
    link: 'https://app.saber.so/#/pools/monkedao/deposit',
    totalSBREmission: 120000,
    totalSunnyEmission: 320000
  },
  {
    symbol: 'USDCet-USDC',
    name: 'USDCet-USDC LP',
    coin: { ...TOKENS.USDCet },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.USDCet, TOKENS.USDC],
    reward: { ...TOKENS.SBR },
    rewardB: { ...TOKENS.SUNNY },
    mintAddress: 'USDCgfM1psLGhAbx99iPA72mTySvUcVq33qhCJpm65c',
    decimals: TOKENS.USDCet.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.SABER,
    sunnyPlatform: 'SunnyxSaber',
    link: 'https://app.saber.so/#/pools/weusdc/deposit',
    totalSBREmission: 220000,
    totalSunnyEmission: 3500000
  },
  {
    symbol: 'BTC-renBTC',
    name: 'BTC-renBTC LP',
    coin: { ...TOKENS.renBTC },
    pc: { ...TOKENS.saberBTC },
    coins: [TOKENS.renBTC, TOKENS.saberBTC],
    reward: { ...TOKENS.SBR },
    rewardB: { ...TOKENS.SUNNY },
    mintAddress: 'SLPbsNrLHv8xG4cTc4R5Ci8kB9wUPs6yn6f7cKosoxs',
    decimals: TOKENS.renBTC.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.SABER,
    sunnyPlatform: 'SunnyxSaber',
    link: 'https://app.saber.so/#/pools/btc/deposit',
    totalSBREmission: 11000,
    totalSunnyEmission: 250000
  }
];
