export const UTILIZATION_THRESHOLD = 100;

export const MAX_POSITIONS_PER_FARM = 3;

export const MIN_SOL_BALANCE_AFTER_DEPOSIT = 0.05;

export const CLOSE_POSITION_OPTIONS = {
  MINIMIZE_TRADING: 10,
  CONVERT_TO_COIN: 11,
  CONVERT_TO_PC: 12
};
