import { NATIVE_SOL, TOKENS } from './tokens';
import { FARM_PLATFORMS } from './farms';
import { toUpper, find } from 'lodash';

export const ORCA_VAULTS = [
  {
    symbol: 'ATLAS-USDC',
    name: 'ATLAS-USDC LP',
    coin: { ...TOKENS.ATLAS },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.ATLAS, TOKENS.USDC],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.ATLAS },
    mintAddress: 'FZ8x1LCRSPDeHBDoAc3Gc6Y7ETCynuHEr5q5YWV7uRCJ',
    decimals: TOKENS.ORCA.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 27,
    maxPositionLimitInUsd: 9000000
  },
  // {
  //   symbol: 'POLIS-USDC',
  //   name: 'POLIS-USDC LP',
  //   coin: { ...TOKENS.POLIS },
  //   pc: { ...TOKENS.USDC },
  //   coins: [TOKENS.POLIS, TOKENS.USDC],
  //   reward: { ...TOKENS.ORCA },
  //   rewardB: { ...TOKENS.POLIS },  //   mintAddress: 'GteBdo9sqE7T41G8AJsaG9WHW48uXBwsLLznmu2TBdgy',
  //   decimals: TOKENS.ORCA.decimals,
  //   dualYield: false,
  //   liquidityMining: false,
  //   totalTulipEmission: 0,
  //   platform: FARM_PLATFORMS.ORCA,
  //   marginIndex: 28,
  //   maxPositionLimitInUsd: 9000000,
  // },
  {
    symbol: 'ORCA-USDC',
    name: 'ORCA-USDC LP',
    coin: { ...TOKENS.ORCA },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.ORCA, TOKENS.USDC],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.ORCA },
    mintAddress: 'n8Mpu28RjeYD7oUX3LG1tPxzhRZh3YYLRSHcHRdS3Zx',
    decimals: TOKENS.ORCA.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 17,
    maxPositionLimitInUsd: 9000000
  },
  {
    symbol: 'BASIS-USDC',
    name: 'BASIS-USDC LP',
    coin: { ...TOKENS.BASIS },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.BASIS, TOKENS.USDC],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.BASIS },
    mintAddress: 'GoaAiajubRgeCFEz9L6mLnSmT2QFegoJDH5tpLfivpj',
    decimals: TOKENS.BASIS.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 57,
    maxPositionLimitInUsd: 9000000
  },
  {
    symbol: 'SAMO-USDC',
    name: 'SAMO-USDC LP',
    coin: { ...TOKENS.SAMO },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.SAMO, TOKENS.USDC],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.SAMO },
    mintAddress: '6VK1ksrmYGMBWUUZfygGF8tHRGpNxQEWv8pfvzQHdyyc',
    decimals: TOKENS.ORCA.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 37,
    maxPositionLimitInUsd: 9000000
  },
  {
    symbol: 'SHDW-USDC',
    name: 'SHDW-USDC LP',
    coin: { ...TOKENS.SHDW },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.SHDW, TOKENS.USDC],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.SHDW },
    mintAddress: 'DJqqvzSuPaWThfzwMjXx7H2ZmHDdwxza6NtFudtuXcpc',
    decimals: TOKENS.ORCA.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 55,
    maxPositionLimitInUsd: 9000000
  },
  {
    symbol: 'SHDW-SOL',
    name: 'SHDW-SOL LP',
    coin: { ...TOKENS.SHDW },
    pc: { ...TOKENS.WSOL },
    coins: [TOKENS.SHDW, NATIVE_SOL],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.SHDW },
    mintAddress: '2ws7g3LBPdctfKn42Di9qxzQtUJ8ZL1aEAX2rGEQMNqh',
    decimals: TOKENS.ORCA.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 56,
    maxPositionLimitInUsd: 9000000
  },
  {
    symbol: 'stSOL-USDC',
    name: 'stSOL-USDC LP',
    coin: { ...TOKENS.stSOL },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.stSOL, TOKENS.USDC],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.wLDO },
    hidden: true,
    mintAddress: 'GtQ1NT7R5aaTiST7K6ZWdMhwDdFxsSFvVFhBo8vyHGAq',
    decimals: TOKENS.ORCA.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 55,
    maxPositionLimitInUsd: 9000000
  },
  {
    symbol: 'wUST-USDC',
    name: 'wUST-USDC LP',
    coin: { ...TOKENS.wUST },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.wUST, TOKENS.USDC],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.wLUNA },
    hidden: true,
    mintAddress: 'J1KfRtP5y2warpD7LdJhfBLPKoWwSqYuovdArSv1mpQ7',
    decimals: TOKENS.ORCA.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 55,
    maxPositionLimitInUsd: 9000000
  },
  {
    symbol: 'CMFI-USDC',
    name: 'CMFI-USDC LP',
    coin: { ...TOKENS.CMFI },
    pc: { ...TOKENS.USDC },
    coins: [TOKENS.CMFI, TOKENS.USDC],
    reward: { ...TOKENS.ORCA },
    rewardB: { ...TOKENS.CMFI },
    mintAddress: '85krvT9DxdYgoFLQDHTAGdvtNuLdAsc4xE5FkVLpN2aR',
    decimals: TOKENS.ORCA.decimals,
    dualYield: false,
    liquidityMining: false,
    totalTulipEmission: 0,
    platform: FARM_PLATFORMS.ORCA,
    marginIndex: 9999,
    maxPositionLimitInUsd: 9000000
  }
];

export const getOrcaVaultBySymbol = (symbol) => {
  return find(ORCA_VAULTS, (vault) => { return toUpper(vault.symbol) === toUpper(symbol); });
};

export const getOrcaVaultByMintAddress = (mintAddress) => {
  return find(ORCA_VAULTS, (vault) => { return vault.mintAddress === mintAddress; });
};
