export function getVaultProgramId(): any;
export function getTokenProgramId(): any;
export function getSaberVaultProgramId(): any;
export function getOrcaVaultProgramId(): any;
export function getVaultInfoAccount(name: any): any;
export function getVaultOldInfoAccount(name: any): any;
export function getVaultAccount(name: any): any;
export function getVaultLpTokenAccount(name: any): any;
export function getVaultPdaAccount(name: any): any;
export function getVaultRewardAccountA(name: any): any;
export function getVaultRewardAccountB(name: any): any;
export function getVaultVersion(name: any): any;
export function getVaultTulipTokenAccount(name: any): any;
export function getVaultTulipRewardPerSlot(name: any): any;
export function getVaultTulipRewardEndSlot(name: any): any;
export function getVaultTulipMint(name: any): any;
export function getVaultSerumOpenOrdersAccount(name: any): any;
export function getVaultSerumVaultSigner(name: any): any;
export function isVersionFourOrFive(name: any): boolean;
export function getFarmProgramId(name: any): any;
export function getFarmPoolId(name: any): any;
export function getFarmPoolAuthority(name: any): any;
export function getFarmLpMintAddress(name: any): any;
export function getFarmPoolLpTokenAccount(name: any): any;
export function getFarmPoolRewardATokenAccount(name: any): any;
export function getFarmPoolRewardBTokenAccount(name: any): any;
export function getFarmFusion(name: any): any;
export function getFarmPoolCoinTokenaccount(name: any): any;
export function getFarmPoolPcTokenaccount(name: any): any;
export function getFarmAmmId(name: any): any;
export function getFarmAmmOpenOrders(name: any): any;
export function getFarmSerumProgramId(name: any): any;
export function getLendingProgramId(): any;
export function getLendingFarmProgramId(): any;
export function getLendingMarketAccount(): any;
export function getLendingFarmManagementAccount(): any;
export function getLendingFarmAccount(name: any): any;
export function getLendingReserve(name: any): any;
export function getLendingReserveFromKey(key: any): any;
export function getPriceFeedsForReserve(name: any): any;
export function isSupportedLendingFarm(name: any): boolean;
export function getLendingReserveByAccount(account: any): any;
export function getOrcaFarmPoolCoinTokenaccount(name: any): any;
export function getOrcaFarmPoolPcTokenaccount(name: any): any;
export function getOrcaLpMintAddress(name: any): any;
export function getOrcaFarmDoubleDip(name: any): any;
export function getOrcaVaultAccount(name: any): any;
export function getOrcaVaultLpAccount(name: any): any;
export function getOrcaVaultFarmMint(name: any): any;
export function getOrcaVaultDdFarmMint(name: any): any;
export function getOrcaVaultGlobalBaseTokenVault(name: any): any;
export function getOrcaVaultGlobalDdBaseTokenVault(name: any): any;
export function getOrcaVaultGlobalFarm(name: any): any;
export function getOrcaVaultGlobalFarmDd(name: any): any;
export function getOrcaVaultGlobalRewardTokenVault(name: any): any;
export function getOrcaVaultGlobalRewardTokenVaultDd(name: any): any;
export function getOrcaVaultConvertAuthority(name: any): any;
export function getOrcaVaultConvertAuthorityDd(name: any): any;
export function getOrcaVaultLpMint(name: any): any;
export function getOrcaVaultSwapPoolTokenAccount(name: any): any;
export function getOrcaVaultRewardMint(name: any): any;
export function getOrcaVaultDdRewardMint(name: any): any;
export function getOrcaVaultFeeAccount(name: any): any;
export function getOrcaFarmPoolId(name: any): any;
export function getOrcaFarmPoolLpTokenAccount(name: any): any;
