export function getVaultProgramId(): any;
export function getTokenProgramId(): any;
export function getVaultInfoAccount(name: any): any;
export function getVaultOldInfoAccount(name: any): any;
export function getVaultAccount(name: any): any;
export function getVaultLpTokenAccount(name: any): any;
export function getVaultPdaAccount(name: any): any;
export function getVaultRewardAccountA(name: any): any;
export function getVaultRewardAccountB(name: any): any;
export function getVaultVersion(name: any): any;
export function getVaultTulipTokenAccount(name: any): any;
export function getVaultTulipRewardPerSlot(name: any): any;
export function getVaultTulipRewardEndSlot(name: any): any;
export function getVaultTulipMint(name: any): any;
export function getVaultSerumOpenOrdersAccount(name: any): any;
export function getVaultSerumVaultSigner(name: any): any;
export function isVersionFourOrFive(name: any): boolean;
export function getFarmProgramId(name: any): any;
export function getFarmPoolId(name: any): any;
export function getFarmPoolAuthority(name: any): any;
export function getFarmLpMintAddress(name: any): any;
export function getFarmPoolLpTokenAccount(name: any): any;
export function getFarmPoolRewardATokenAccount(name: any): any;
export function getFarmPoolRewardBTokenAccount(name: any): any;
export function getFarmFusion(name: any): any;
export function getFarmPoolCoinTokenaccount(name: any): any;
export function getFarmPoolPcTokenaccount(name: any): any;
export function getFarmAmmId(name: any): any;
export function getFarmAmmOpenOrders(name: any): any;
export function getFarmSerumProgramId(name: any): any;
export function getLendingProgramId(): any;
export function getLendingFarmProgramId(): any;
export function getLendingMarketAccount(): any;
export function getLendingFarmManagementAccount(): any;
export function getLendingFarmAccount(name: any): any;
export function getLendingReserve(name: any): any;
export function getLendingReserveFromKey(key: any): any;
export function getPriceFeedsForReserve(name: any): any;
export function isSupportedLendingFarm(name: any): boolean;
export function getLendingReserveByAccount(account: any): any;
