export function getReserveByName(name: any): {
    name: string;
    account: string;
    mintAddress: string;
    liquiditySupplyTokenAccount: string;
    liquidityFeeReceiver: string;
    collateralTokenMint: string;
    collateralTokenSupply: string;
    destinationCollateralTokenAccount: string;
    quoteTokenMint: string;
    decimals: number;
    visible: boolean;
    borrowDisabled?: undefined;
} | {
    name: string;
    account: string;
    mintAddress: string;
    liquiditySupplyTokenAccount: string;
    liquidityFeeReceiver: string;
    collateralTokenMint: string;
    collateralTokenSupply: string;
    destinationCollateralTokenAccount: string;
    quoteTokenMint: string;
    decimals: number;
    visible: boolean;
    borrowDisabled: boolean;
};
export function getReserveByMintAddress(mintAddress: any): {
    name: string;
    account: string;
    mintAddress: string;
    liquiditySupplyTokenAccount: string;
    liquidityFeeReceiver: string;
    collateralTokenMint: string;
    collateralTokenSupply: string;
    destinationCollateralTokenAccount: string;
    quoteTokenMint: string;
    decimals: number;
    visible: boolean;
    borrowDisabled?: undefined;
} | {
    name: string;
    account: string;
    mintAddress: string;
    liquiditySupplyTokenAccount: string;
    liquidityFeeReceiver: string;
    collateralTokenMint: string;
    collateralTokenSupply: string;
    destinationCollateralTokenAccount: string;
    quoteTokenMint: string;
    decimals: number;
    visible: boolean;
    borrowDisabled: boolean;
};
export function getReserveByCollateralTokenMint(collateralTokenMint: any): {
    name: string;
    account: string;
    mintAddress: string;
    liquiditySupplyTokenAccount: string;
    liquidityFeeReceiver: string;
    collateralTokenMint: string;
    collateralTokenSupply: string;
    destinationCollateralTokenAccount: string;
    quoteTokenMint: string;
    decimals: number;
    visible: boolean;
    borrowDisabled?: undefined;
} | {
    name: string;
    account: string;
    mintAddress: string;
    liquiditySupplyTokenAccount: string;
    liquidityFeeReceiver: string;
    collateralTokenMint: string;
    collateralTokenSupply: string;
    destinationCollateralTokenAccount: string;
    quoteTokenMint: string;
    decimals: number;
    visible: boolean;
    borrowDisabled: boolean;
};
